# Generated by Django 5.2.4 on 2025-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=10, null=True)),
                ("correo", models.EmailField(max_length=254, null=True)),
                ("fecha_nacimiento", models.DateField()),
                ("ciudad", models.CharField(max_length=100, null=True)),
                (
                    "nivel_educativo",
                    models.CharField(
                        choices=[
                            ("Bachillerato", "Bachillerato"),
                            ("TEC", "Técnico"),
                            ("TGL", "Tecnólogo"),
                            ("PRE", "Pregrado"),
                            ("ESP", "Especializacion"),
                            ("MAE", "Maestría"),
                            ("DOC", "Doctorado"),
                        ],
                        default="Bachillerato",
                        max_length=100,
                    ),
                ),
                ("especialidad", models.CharField(max_length=100)),
                ("anos_experiencia", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_vinculacion", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
